export const METROAREA = [
    
    { label:'metro'},
    { label:'New York-Newark, NY-NJ-CT-PA'},
    { label:'Boston-Worcester-Providence, MA-RI-NH-ME'},
    { label:'Hartford-West Hartford, CT-MA'},
    { label:'Albany-Schenectady, NY-MA'},
    { label:'Pittsburgh-New Castle-Weirton, PA-OH-WV'},
    { label:'Harrisburg-Lebanon, PA'},
    { label:'Philadelphia-Reading-Camden, PA-NJ-DE-MD'},
    { label:'Washington-Baltimore-Arlington, DC-MD-VA-WV-PA'},
    { label:'Virginia Beach-Norfolk, VA-NC'},
    { label:'Charlotte-Concord, NC-SC'},
    { label:'Raleigh-Durham-Chapel Hill, NC'},
    { label:'Atlanta--Athens-Clarke County--Sandy Springs, GA-AL'},
    { label:'Palm Bay-Melbourne-Titusville, FL'},
    { label:'Miami-Fort Lauderdale-Port St. Lucie, FL'},
    { label:'Birmingham-Hoover-Talladega, AL'},
    { label:'Huntsville-Decatur-Albertville, AL'},
    { label:'Columbus-Marion-Zanesville, OH'},
    { label:'Dayton-Springfield-Sidney, OH'},
    { label:'Cleveland-Akron-Canton, OH'},
    { label:'Cincinnati-Wilmington-Maysville, OH-KY-IN'},
    { label:'Indianapolis-Carmel-Muncie, IN'},
    { label:'Detroit-Warren-Ann Arbor, MI'},
    { label:'Davenport-Moline, IA-IL'},
    { label:'Milwaukee-Racine-Waukesha, WI'},
    { label:'Minneapolis-St. Paul, MN-WI'},
    { label:'Chicago-Naperville, IL-IN-WI'},
    { label:'St. Louis-St. Charles-Farmington, MO-IL'},
    { label:'Kansas City-Overland Park-Kansas City, MO-KS'},
    { label:'Omaha-Council Bluffs-Fremont, NE-IA'},
    { label:'Austin-Round Rock, TX'},
    { label:'Dallas-Fort Worth, TX-OK'},
    { label:'Houston-The Woodlands, TX'},
    { label:'San Antonio-New Braunfels-Pearsall, TX'},
    { label:'Corpus Christi-Kingsville-Alice, TX'},
    { label:'Denver-Aurora, CO'},
    { label:'Phoenix-Mesa-Scottsdale, AZ'},
    { label:'Albuquerque-Santa Fe-Las Vegas, NM'},
    { label:'Las Vegas-Henderson, NV-AZ'},
    { label:'Los Angeles-Long Beach, CA'},
    { label:'San Jose-San Francisco-Oakland, CA'},
    { label:'Sacramento-Roseville, CA-NV'},
    { label:'Portland-Vancouver-Salem, OR-WA'},
    { label:'Seattle-Tacoma, WA'},
    
    ];
    